### ISSUE TITLE
Bias-corrected VAR running issue on eigenvalues non-convergence

### ISSUE THREAD

**Issue by dake-li** [dake-li/lp_var_simul#12]
https://github.com/dake-li/lp_var_simul/blob/b7bd3ad0d10ff5d18c517351a2bb2e5c009fe923/Estimation_Routines/VAR_CorrectBias.m#L67

**Comment by mikkelpm** [comment]
I agree that the signs in lines 13 and 62 seem off. We should check the code on a DGP where we know the Pope correction in closed form, such as an AR(1), or a VAR(1) with independent series.

It's still not clear why the eigenvalue can't be computed, though. Let's see what the server output looks like.

**Comment by ckwolf92** [comment]
I agree that the signs in lines 13 and 62 seem incorrect. I also checked the Kilian (1998) paper again and could not find a problem with our implementation. In terms of next steps, I thus agree with Mikkel that we should (i) wait for the server output and (ii) check the code for a case where the bias correction is known.

**Comment by mikkelpm** [comment]
> could not find a problem with our implementation

But it seems likely that the sign is a mistake, so we should just confirm this quickly with a special case.
